name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make


    - name: Upload Firmware Directory # 11. 导出固件目录
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: libjulesz.so
        path: images
